/* Generated By:JavaCC: Do not edit this line. Lexical.java */
//package for all files in the lexical/ directory
package lexical;
//public class
public class Lexical implements LexicalConstants {

  static final public void g_program() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case t_strict:
      g_strict();
      break;
    default:
      jj_la1[0] = jj_gen;
      ;
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case t_import:
      g_import();
      break;
    default:
      jj_la1[1] = jj_gen;
      ;
    }
    g_body();

  }

  static final public void g_body() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case t_conditional:
    case t_switch:
    case t_for:
    case t_while:
    case t_output:
    case t_try:
    case t_var:
      g_instruction();
      break;
    case t_method:
      g_method();
      break;
    default:
      jj_la1[2] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    g_more_body();

  }

  static final public void g_more_body() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case t_conditional:
    case t_switch:
    case t_for:
    case t_while:
    case t_output:
    case t_try:
    case t_method:
    case t_var:
      g_body();
      break;
    default:
      jj_la1[3] = jj_gen;
      ;
    }

  }

  static final public void g_instruction() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case t_var:
      g_declaration();
      break;
    case t_conditional:
      g_conditional();
      break;
    case t_while:
      g_while();
      break;
    case t_for:
      g_for();
      break;
    case t_try:
      g_try();
      break;
    case t_output:
      g_output();
      break;
    case t_switch:
      g_switch();
      break;
    default:
      jj_la1[4] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }

  }

  static final public void g_declaration() throws ParseException {
    jj_consume_token(t_var);
    jj_consume_token(t_var_name);
    jj_consume_token(t_assignment);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case t_bool:
    case t_input:
    case t_null:
    case t_var_name:
    case t_char_value:
    case t_string_value:
    case t_int_value:
    case t_float_value:
    case t_snot_value:
    case t_complex_value:
      g_declaration_single();
      break;
    case t_data_type:
      g_declaration_complete();
      break;
    default:
      jj_la1[5] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }

  }

  static final public void g_declaration_single() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case t_bool:
    case t_var_name:
    case t_char_value:
    case t_string_value:
    case t_int_value:
    case t_float_value:
    case t_snot_value:
    case t_complex_value:
      g_value();
      break;
    case t_null:
      jj_consume_token(t_null);
      break;
    case t_input:
      g_input();
      break;
    default:
      jj_la1[6] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    g_more_vars();

  }

  static final public void g_declaration_complete() throws ParseException {
    jj_consume_token(t_data_type);
    jj_consume_token(t_parenthesis_group_open);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case t_bool:
    case t_var_name:
    case t_char_value:
    case t_string_value:
    case t_int_value:
    case t_float_value:
    case t_snot_value:
    case t_complex_value:
      g_value();
      break;
    case t_null:
      jj_consume_token(t_null);
      break;
    case t_input:
      g_input();
      break;
    default:
      jj_la1[7] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    jj_consume_token(t_parenthesis_group_close);

  }

  static final public void g_value() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case t_char_value:
    case t_string_value:
      g_text_value();
      break;
    case t_int_value:
    case t_float_value:
    case t_snot_value:
    case t_complex_value:
      g_number_value();
      break;
    case t_var_name:
      jj_consume_token(t_var_name);
      break;
    case t_bool:
      jj_consume_token(t_bool);

      break;
    default:
      jj_la1[8] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void g_text_value() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case t_string_value:
      jj_consume_token(t_string_value);
      break;
    case t_char_value:
      jj_consume_token(t_char_value);

      break;
    default:
      jj_la1[9] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void g_number_value() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case t_int_value:
      jj_consume_token(t_int_value);
      break;
    case t_float_value:
      jj_consume_token(t_float_value);
      break;
    case t_complex_value:
      jj_consume_token(t_complex_value);
      break;
    case t_snot_value:
      jj_consume_token(t_snot_value);

      break;
    default:
      jj_la1[10] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void g_more_vars() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case t_comma:
      jj_consume_token(t_comma);
      jj_consume_token(t_var_name);
      jj_consume_token(t_assignment);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case t_bool:
      case t_input:
      case t_null:
      case t_var_name:
      case t_char_value:
      case t_string_value:
      case t_int_value:
      case t_float_value:
      case t_snot_value:
      case t_complex_value:
        g_declaration_single();
        break;
      case t_data_type:
        g_declaration_complete();
        break;
      default:
        jj_la1[11] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    default:
      jj_la1[12] = jj_gen;
      ;
    }

  }

  static final public void g_import() throws ParseException {
    jj_consume_token(t_import);
    jj_consume_token(t_string_value);
    g_more_imports();

  }

  static final public void g_more_imports() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case t_comma:
      jj_consume_token(t_comma);
      jj_consume_token(t_string_value);
      break;
    default:
      jj_la1[13] = jj_gen;
      ;
    }

  }

  static final public void g_strict() throws ParseException {
    jj_consume_token(t_strict);

  }

  static final public void g_conditional() throws ParseException {
    jj_consume_token(t_conditional);
    jj_consume_token(t_parenthesis_group_open);
    g_condition();
    jj_consume_token(t_parenthesis_group_close);
    jj_consume_token(t_parenthesis_group_open);
    g_instruction();
    jj_consume_token(t_parenthesis_group_close);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case t_elif:
      g_elif();
      break;
    default:
      jj_la1[14] = jj_gen;
      ;
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case t_else:
      g_else();
      break;
    default:
      jj_la1[15] = jj_gen;
      ;
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case t_finally:
      g_finally();
      break;
    default:
      jj_la1[16] = jj_gen;
      ;
    }

  }

  static final public void g_condition() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case t_parenthesis_group_open:
      g_logic_expression();
      break;
    case t_bool:
    case t_var_name:
    case t_char_value:
    case t_string_value:
    case t_int_value:
    case t_float_value:
    case t_snot_value:
    case t_complex_value:
      g_comparison();

      break;
    default:
      jj_la1[17] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void g_comparison() throws ParseException {
    g_value();
    jj_consume_token(t_comparison_operator);
    g_value();

  }

  static final public void g_logic_expression() throws ParseException {
    jj_consume_token(t_parenthesis_group_open);
    g_comparison();
    jj_consume_token(t_parenthesis_group_close);
    jj_consume_token(t_logic_operator);
    jj_consume_token(t_parenthesis_group_open);
    g_comparison();
    jj_consume_token(t_parenthesis_group_close);
    g_more_logic_expressions();

  }

  static final public void g_more_logic_expressions() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case t_parenthesis_group_open:
      g_logic_expression();
      break;
    default:
      jj_la1[18] = jj_gen;
      ;
    }

  }

  static final public void g_else() throws ParseException {
    jj_consume_token(t_else);
    jj_consume_token(t_parenthesis_group_open);
    g_instruction();
    jj_consume_token(t_parenthesis_group_close);

  }

  static final public void g_elif() throws ParseException {
    jj_consume_token(t_elif);
    jj_consume_token(t_parenthesis_group_open);
    g_condition();
    jj_consume_token(t_parenthesis_group_close);
    jj_consume_token(t_parenthesis_group_open);
    g_instruction();
    jj_consume_token(t_parenthesis_group_close);
    g_more_elifs();

  }

  static final public void g_more_elifs() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case t_elif:
      g_elif();
      break;
    default:
      jj_la1[19] = jj_gen;
      ;
    }

  }

  static final public void g_while() throws ParseException {
    jj_consume_token(t_while);
    jj_consume_token(t_parenthesis_group_open);
    g_condition();
    jj_consume_token(t_parenthesis_group_close);
    jj_consume_token(t_parenthesis_group_open);
    g_instruction();
    jj_consume_token(t_parenthesis_group_close);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case t_finally:
      g_finally();
      break;
    default:
      jj_la1[20] = jj_gen;
      ;
    }

  }

  static final public void g_for() throws ParseException {
    jj_consume_token(t_for);
    jj_consume_token(t_parenthesis_group_open);
    g_range();
    jj_consume_token(t_parenthesis_group_close);
    jj_consume_token(t_parenthesis_group_open);
    g_instruction();
    jj_consume_token(t_parenthesis_group_close);

  }

  static final public void g_range() throws ParseException {
    jj_consume_token(t_var_name);
    jj_consume_token(t_membership_operator);
    jj_consume_token(t_range);
    jj_consume_token(t_parenthesis_group_open);
    g_number_value();
    jj_consume_token(t_comma);
    g_number_value();
    jj_consume_token(t_parenthesis_group_close);

  }

  static final public void g_try() throws ParseException {
    jj_consume_token(t_try);
    jj_consume_token(t_parenthesis_group_open);
    g_instruction();
    jj_consume_token(t_parenthesis_group_close);
    g_catch();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case t_finally:
      g_finally();
      break;
    default:
      jj_la1[21] = jj_gen;
      ;
    }

  }

  static final public void g_catch() throws ParseException {
    jj_consume_token(t_catch);
    jj_consume_token(t_parenthesis_group_open);
    jj_consume_token(t_parenthesis_group_close);
    jj_consume_token(t_parenthesis_group_open);
    g_instruction();
    jj_consume_token(t_parenthesis_group_close);
    g_more_catchs();

  }

//add exception
  static final public void g_more_catchs() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case t_catch:
      g_catch();
      break;
    default:
      jj_la1[22] = jj_gen;
      ;
    }

  }

  static final public void g_finally() throws ParseException {
    jj_consume_token(t_finally);
    jj_consume_token(t_parenthesis_group_open);
    g_instruction();
    jj_consume_token(t_parenthesis_group_close);

  }

  static final public void g_not_yet() throws ParseException {
    jj_consume_token(t_not_yet);

  }

  static final public void g_do_while() throws ParseException {
    jj_consume_token(t_do);
    jj_consume_token(t_parenthesis_group_open);
    g_instruction();
    jj_consume_token(t_parenthesis_group_close);
    jj_consume_token(t_while);
    jj_consume_token(t_parenthesis_group_open);
    g_condition();
    jj_consume_token(t_parenthesis_group_close);

  }

  static final public void g_input() throws ParseException {
    jj_consume_token(t_input);
    jj_consume_token(t_parenthesis_group_open);
    g_text_value();
    jj_consume_token(t_parenthesis_group_close);

  }

  static final public void g_output() throws ParseException {
    jj_consume_token(t_output);
    jj_consume_token(t_parenthesis_group_open);
    g_text_value();
    jj_consume_token(t_parenthesis_group_close);

  }

  static final public void g_switch() throws ParseException {
    jj_consume_token(t_switch);
    jj_consume_token(t_parenthesis_group_open);
    jj_consume_token(t_var_name);
    jj_consume_token(t_parenthesis_group_close);
    jj_consume_token(t_parenthesis_group_open);
    g_case();
    g_default();
    jj_consume_token(t_parenthesis_group_close);

  }

  static final public void g_case() throws ParseException {
    jj_consume_token(t_case);
    jj_consume_token(t_parenthesis_group_open);
    g_value();
    jj_consume_token(t_parenthesis_group_close);
    jj_consume_token(t_parenthesis_group_open);
    g_instruction();
    jj_consume_token(t_parenthesis_group_close);
    g_more_cases();

  }

  static final public void g_more_cases() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case t_case:
      g_case();
      break;
    default:
      jj_la1[23] = jj_gen;
      ;
    }

  }

  static final public void g_default() throws ParseException {
    jj_consume_token(t_default);
    jj_consume_token(t_parenthesis_group_open);
    g_instruction();
    jj_consume_token(t_parenthesis_group_close);

  }

  static final public void g_method() throws ParseException {
    jj_consume_token(t_method);
    jj_consume_token(t_parenthesis_group_open);
    g_parameter();
    jj_consume_token(t_parenthesis_group_close);
    jj_consume_token(t_parenthesis_group_open);
    g_instruction();
    g_return();
    jj_consume_token(t_parenthesis_group_close);

  }

  static final public void g_parameter() throws ParseException {
    jj_consume_token(t_var_name);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case t_assignment:
      jj_consume_token(t_assignment);
      g_value();
      break;
    default:
      jj_la1[24] = jj_gen;
      ;
    }
    g_more_parameters();

  }

  static final public void g_more_parameters() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case t_comma:
      jj_consume_token(t_comma);
      g_parameter();
      break;
    default:
      jj_la1[25] = jj_gen;
      ;
    }

  }

  static final public void g_return() throws ParseException {
    jj_consume_token(t_return);
    g_value();

  }

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public LexicalTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[26];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static private int[] jj_la1_2;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
      jj_la1_init_2();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x0,0x0,0x43020080,0x43020080,0x43020080,0x2000,0x2000,0x2000,0x2000,0x0,0x0,0x2000,0x20000000,0x20000000,0x100,0x1000,0x0,0x2200,0x200,0x100,0x0,0x0,0x0,0x40000,0x4000,0x20000000,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x20000000,0x10000000,0x40082000,0x40082000,0x40002000,0x20041,0x20001,0x20001,0x0,0x0,0x0,0x20041,0x0,0x0,0x0,0x0,0x8000,0x0,0x0,0x0,0x8000,0x8000,0x4000,0x0,0x0,0x0,};
   }
   private static void jj_la1_init_2() {
      jj_la1_2 = new int[] {0x0,0x0,0x0,0x0,0x0,0x3f80,0x3f80,0x3f80,0x3f80,0x300,0x3c00,0x3f80,0x0,0x0,0x0,0x0,0x0,0x3f80,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,};
   }

  /** Constructor with InputStream. */
  public Lexical(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Lexical(java.io.InputStream stream, String encoding) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser.  ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new LexicalTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 26; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 26; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public Lexical(java.io.Reader stream) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new LexicalTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 26; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 26; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public Lexical(LexicalTokenManager tm) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 26; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(LexicalTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 26; i++) jj_la1[i] = -1;
  }

  static private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  static final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  static private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;

  /** Generate ParseException. */
  static public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[78];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 26; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
          if ((jj_la1_2[i] & (1<<j)) != 0) {
            la1tokens[64+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 78; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

                       }
